apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.config.namespace }}
data:
  MONGODB_URI: {{ .Values.config.mongodbUri | quote }}
  SESSION_SECRET: {{ .Values.config.sessionSecret | quote }}
  PORT: {{ .Values.config.port | quote }}




# Steps:

# kubectl apply -f configmap.yaml -n abdullah

# kubectl apply -f secret.yaml -n abdullah
# kubectl apply -f deployment.yaml -n abdullah

# kubectl get configmap -n abdullah
# kubectl get secret -n abdullah
# after changing values

# kubectl apply -f configmap.yaml -n abdullah
# kubectl apply -f secret.yaml -n abdullah

# kubectl rollout restart deployment userprofile-deployment -n abdullah





