apiVersion: v1
kind: Secret
metadata:
  name: abdullah-secret
  namespace: abdullah
type: Opaque
data:
  EMAIL_USER: Y2hhZ2FudHl0ZWphMjUwMkBnbWFpbC5jb20=
  EMAIL_PASS: eXhvciBianVrIHJkbnQgYWx6cA==


# echo -n "chagantyteja2502@gmail.com" | base64
# # → Y2hhZ2FudHl0ZWphMjUwMkBnbWFpbC5jb20=
# echo -n "yxoq bjuk rdnt alzp" | base64
# # → eXhvciBianVrIHJkbnQgYWx6cA==

