apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: abdullah-sc
  namespace: abdullah
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp2
# allowedTopologies:
# - matchLabelExpressions:
#   - key: topology.kubernetes.io/zone
#     values:
#       - ap-south-1a   # replace with your node's AZ



# # Apply StorageClass (if not already applied)
# kubectl apply -f storageclass.yaml

# # Apply PVC
# kubectl apply -f pvc.yaml -n abdullah

# # Apply MongoDB Deployment
# kubectl apply -f deployment.yaml -n abdullah
